version: '3.8'
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - '5001:5001'
  #   volumes:
  #     - ./backend:/usr/src/app/backend
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - NODE_ENV=production
  #   restart: always

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend:/usr/src/app/frontend
  #   restart: always
  #   depends_on:
  #     - backend

  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data:
